# Site settings
url: "https://portfolios.18f.gov" # the base hostname & protocol for your sites
title: "18F Portfolios: Digital service delivery"
description: "As 18F teams continue to work with agencies that share a common mission or face similar challenges, our staff have begun to acquire expertise that can be used to address common problems in these domain areas."
github_repo: https://github.com/18F/portfolios/blob/release
baseurl: "" # the subpath of your site, e.g. /blog
permalink: pretty
url: "https://18f.gsa.gov" # the base hostname & protocol for your sites
localhost: "localhost:4000"
env: "production"
logo: /assets/img/logos/18F-Logo-Bright-S.png
tag_dir: tags

related_posts: 3

analytics:
  google:
    code: 'UA-48605964-19' # Microsites at 18F/GSA analytics code
  dap:
    agency: GSA    # Change this to your agency
    subagency: 18F # Change this to your agency

collections:
  portfolios:
    output: true
    permalink: /portfolios/:path/
  portfolios_projects:
    output: true
    permalink: /portfolios/:path/

defaults:
 - scope:
     path: "_portfolios"
   values:
     layout: portfolio
 - scope:
     path: "_portfolios_projects"
   values:
     layout: portfolio-project-page

footer:
  image: /assets/img/logos/18F-Logo-M.png
  email:
  twitter:
    - 18f
    - usgsa
  text: This site was built using <a href="https://federalist.18f.gov/" target="_blank">Federalist, from 18F</a>. # Change to a tag line for your agency

# Build settings
markdown: kramdown
highlighter: rouge

# Compress Sass
# sass:
#   style: compressed

exclude:
- .about.yml
- .cfignore
- .codeclimate.yml
- .gitignore
- .gitmodules
- .hound.yml
- 404.html
- api-endpoints
- bin
- build
- circle.yml
- config_blog.rb
- CONTRIBUTING.md
- docker-compose.yml
- docker_entrypoint.rb
- Dockerfile
- examples/
- favicon.ico
- feed*
- Gemfile*
- ISSUE_TEMPLATE.md
- killport
- LICENSE.md
- node_modules
- package.json
- pages/our-work.html
- PULL_REQUEST_TEMPLATE.md
- README.md
- spec/
- system-security-plan.yml
- tests/
- tests/schema/tags.yml
- tmp/
- vendor

# jekyll plugins
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll_pages_api_search
  - jekyll_oembed

# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  skip_index: true

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
