url: "https://portfolios.18f.gov" # the base hostname & protocol for your sites
title: "18F Portfolios: Digital service delivery"
description: "As 18F teams continue to work with agencies that share a common mission or face similar challenges, our staff have begun to acquire expertise that can be used to address common problems in these domain areas."
github_repo: https://github.com/18F/portfolios/blob/release

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed

analytics:
  google:
    code: 'UA-48605964-19' # Microsites at 18F/GSA analytics code
  dap:
    agency: GSA    # Change this to your agency
    subagency: 18F # Change this to your agency

jekyll_pages_api_search:
  skip_index: true

collections:
  portfolios:
    output: true
    permalink: /portfolios/:path/
  portfolios_projects:
    output: true
    permalink: /portfolios/:path/

defaults:
 -
   scope:
     path: "_portfolios"
   values:
     layout: portfolio
 -
   scope:
     path: "_portfolios_projects"
   values:
     layout: portfolio-project-page

env: "development"
exclude:
- .about.yml
- .cfignore
- .codeclimate.yml
- .gitignore
- .gitmodules
- .hound.yml
- 404.html
- api-endpoints
- bin
- build
- circle.yml
- config_blog.rb
- CONTRIBUTING.md
- docker-compose.yml
- docker_entrypoint.rb
- Dockerfile
- examples/
- favicon.ico
- feed*
- Gemfile*
- humans.txt
- ISSUE_TEMPLATE.md
- killport
- LICENSE.md
- node_modules
- package.json
- pages/our-work.html
- PULL_REQUEST_TEMPLATE.md
- README.md
- robots.txt
- search-index*
- sitemap.xml
- spec/
- system-security-plan.yml
- tests/
- tests/schema/tags.yml
- tmp/
- vendor
- _posts/
- _about/
- _authors/
- _join/
- _products_projects/
- _services_projects/
- _styleguide
